# Generated by Django 2.1.3 on 2018-11-28 19:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('Created_On', models.DateField(auto_now_add=True)),
                ('Category', models.CharField(choices=[('Donor', (('member', 'Member'), ('regular', 'Regular'), ('first_time', 'First_Time'), ('annual', 'Annual'), ('grant', 'Grant'), ('otherdonor', 'Otherdonor'))), ('Vendor', (('biller', 'Biller'), ('contractor', 'Contractor'), ('seller', 'Seller'))), ('unknown', 'Unknown'), ('other', 'Other')], default='Unknown', max_length=20)),
                ('Contact_Format', models.CharField(choices=[('Company', 'Company'), ('individual', 'Individual'), ('couple', 'Couple'), ('other', 'Other')], default='Other', max_length=20)),
                ('Company', models.CharField(blank=True, max_length=50)),
                ('First_Name1', models.CharField(blank=True, max_length=30)),
                ('Last_Name1', models.CharField(blank=True, max_length=30)),
                ('First_Name2', models.CharField(blank=True, max_length=30)),
                ('Last_Name2', models.CharField(blank=True, max_length=30)),
                ('Address_Number', models.CharField(blank=True, max_length=20)),
                ('Address_Street', models.CharField(blank=True, max_length=30)),
                ('Address_Street2', models.CharField(blank=True, max_length=30)),
                ('Address_City', models.CharField(blank=True, max_length=30)),
                ('Address_State', models.CharField(blank=True, max_length=30)),
                ('Address_Postal_Code', models.CharField(blank=True, max_length=30)),
                ('Address_Country', models.CharField(blank=True, default='USA', max_length=30)),
                ('Phone1', models.CharField(blank=True, max_length=20)),
                ('Phone2', models.CharField(blank=True, max_length=20)),
                ('Email1', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('Email2', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('Note', models.TextField(blank=True)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
