# Generated by Django 2.1.4 on 2018-12-05 07:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('Created_On', models.DateField(auto_now_add=True)),
                ('Contact_Category', models.CharField(choices=[('donor', 'Donor'), ('vendor', 'Vendor')], default='Donor', max_length=20)),
                ('Address', models.CharField(blank=True, max_length=255)),
                ('City', models.CharField(blank=True, max_length=255)),
                ('State', models.CharField(blank=True, max_length=2)),
                ('Postal_code', models.CharField(blank=True, max_length=20)),
                ('Country', models.CharField(blank=True, default='USA', max_length=30)),
                ('Company', models.CharField(blank=True, max_length=50)),
                ('First_Name', models.CharField(blank=True, max_length=30)),
                ('Last_Name', models.CharField(blank=True, max_length=30)),
                ('Email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('Phone', models.CharField(blank=True, max_length=20)),
                ('First_Name2', models.CharField(blank=True, max_length=30)),
                ('Last_Name2', models.CharField(blank=True, max_length=30)),
                ('Phone2', models.CharField(blank=True, max_length=20)),
                ('Email2', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('Note', models.TextField(blank=True)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Format', models.CharField(choices=[('business', 'Business'), ('individual', 'Individual'), ('couple', 'Couple'), ('other', 'Other')], default='Other', max_length=20)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('Company', 'Owner')},
        ),
    ]
