# Generated by Django 2.1.4 on 2018-12-07 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20181206_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['Company', 'Last_Name', 'First_Name'], 'verbose_name_plural': 'Contacts'},
        ),
    ]
