# Generated by Django 2.1.3 on 2018-11-27 17:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('booktype', models.CharField(choices=[('Donor', (('member', 'Member'), ('regular', 'Regular'), ('first_time', 'First_Time'), ('annual', 'Annual'), ('grant', 'Grant'), ('otherdonor', 'Otherdonor'))), ('Vendor', (('biller', 'Biller'), ('contractor', 'Contractor'), ('seller', 'Seller'))), ('unknown', 'Unknown'), ('other', 'Other')], default='Unknown', max_length=20)),
                ('contacttype', models.CharField(choices=[('company', 'Company'), ('individual', 'Individual'), ('couple', 'Couple'), ('other', 'Other')], default='Other', max_length=20)),
                ('company', models.CharField(blank=True, max_length=50)),
                ('first_name1', models.CharField(blank=True, max_length=30)),
                ('last_name1', models.CharField(blank=True, max_length=30)),
                ('first_name2', models.CharField(blank=True, max_length=30)),
                ('last_name2', models.CharField(blank=True, max_length=30)),
                ('address_number', models.CharField(blank=True, max_length=20)),
                ('address_street', models.CharField(blank=True, max_length=30)),
                ('address_street2', models.CharField(blank=True, max_length=30)),
                ('address_city', models.CharField(blank=True, max_length=30)),
                ('address_state', models.CharField(blank=True, max_length=30)),
                ('address_postalcode', models.CharField(blank=True, max_length=30)),
                ('address_country', models.CharField(blank=True, default='USA', max_length=30)),
                ('phone1', models.CharField(blank=True, max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('email1', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('email2', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('note', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'contacts',
            },
        ),
    ]
