# Generated by Django 2.1.3 on 2018-11-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easydonorapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'Contacts'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='address_city',
            new_name='Address_City',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='address_country',
            new_name='Address_Country',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='address_number',
            new_name='Address_Number',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='address_postalcode',
            new_name='Address_Postal_Code',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='address_state',
            new_name='Address_State',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='address_street',
            new_name='Address_Street',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='address_street2',
            new_name='Address_Street2',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='booktype',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='contacttype',
            new_name='Contact_Format',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='created_on',
            new_name='Created_On',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email1',
            new_name='Email1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='email2',
            new_name='Email2',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='note',
            new_name='Note',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='owner',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone1',
            new_name='Phone1',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='phone2',
            new_name='Phone2',
        ),
    ]
