# Generated by Django 2.1.3 on 2018-11-28 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easydonorapp', '0002_auto_20181127_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Owner',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
